import * as path from 'path';
import { transformSync } from 'esbuild';
import type { IFilesystemHost } from './fs-host';

export interface CollectedFiles {
  /** .js source files to be combined into the chunk */
  sourceFiles: string[];
  /** .json data files that are require()'d by the source files at runtime */
  dataFiles: string[];
}

/**
 * Collect all .js files in a submodule directory, excluding test/, node_modules/,
 * *.d.ts, *.bundled.js, *.combined.js, *.js.map.
 *
 * Also scans the collected .js files for require() calls that reference .json files,
 * and returns those as dataFiles.
 */
export function collectFiles(host: IFilesystemHost, submoduleDir: string): CollectedFiles {
  const sourceFiles: string[] = [];
  function walk(dir: string) {
    for (const entry of host.readdir(dir)) {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory) {
        if (entry.name === 'test' || entry.name === 'node_modules') continue;
        walk(full);
      } else if (
        entry.name.endsWith('.js') &&
        !entry.name.endsWith('.d.ts') &&
        !entry.name.endsWith('.bundled.js') &&
        !entry.name.endsWith('.combined.js') &&
        !entry.name.endsWith('.js.map')
      ) {
        sourceFiles.push(full);
      }
    }
  }
  walk(submoduleDir);

  // Scan source files for require("...json") to find data files
  const dataFiles = new Set<string>();
  for (const filePath of sourceFiles) {
    const source = host.readFile(filePath);
    const fileDir = path.dirname(filePath);
    // Match require("...json") and require('...json')
    const re = /require\(["']([^"']+\.json)["']\)/g;
    let m;
    while ((m = re.exec(source)) !== null) {
      const reqPath = m[1];
      if (!reqPath.startsWith('.')) continue; // skip non-relative (package requires)
      const resolved = path.resolve(fileDir, reqPath);
      if (host.exists(resolved)) {
        dataFiles.add(resolved);
      }
    }
    // Also match require(path.join(__dirname, "...json"))
    const pathJoinRe = /require\(path\.join\(__dirname,\s*["']([^"']+\.json)["']\)\)/g;
    while ((m = pathJoinRe.exec(source)) !== null) {
      const resolved = path.resolve(fileDir, m[1]);
      if (host.exists(resolved)) {
        dataFiles.add(resolved);
      }
    }
  }

  return { sourceFiles, dataFiles: [...dataFiles] };
}

/**
 * Compute the registry key for a file relative to the submodule root.
 * e.g. /abs/aws-s3/lib/bucket.js -> "./lib/bucket"
 */
export function registryKey(filePath: string, submoduleDir: string): string {
  let rel = path.relative(submoduleDir, filePath).replace(/\\/g, '/');
  rel = rel.replace(/\.js$/, '');
  return './' + rel;
}

/**
 * Strip .js extensions from relative require() paths.
 * Registry keys don't have .js, so the runtime resolver needs clean paths.
 */
export function rewriteRequires(source: string): string {
  return source.replace(/require\(["']([^"']+)["']\)/g, (match, reqPath: string) => {
    if (!reqPath.startsWith('.')) return match;
    if (reqPath.endsWith('.js')) {
      return `require("${reqPath.slice(0, -3)}")`;
    }
    return match;
  });
}

/**
 * Generate the combined file content for a submodule.
 *
 * @param submoduleName - Name of the submodule (e.g. "aws-s3")
 * @param modules - Map of registry key -> source code
 * @returns The combined file content as a string
 */
export function generateCombinedSource(submoduleName: string, modules: Map<string, string>): string {
  const lines: string[] = [];

  lines.push('"use strict";');
  lines.push(`// Combined module file for ${submoduleName}`);
  lines.push('// Generated by @aws-cdk/chunkify — do not edit');
  lines.push('');
  lines.push('var __modules = {};');
  lines.push('var __cache = {};');
  lines.push('');

  // __req: the internal module loader
  lines.push('function __req(id) {');
  lines.push('  if (__cache[id]) return __cache[id].exports;');
  lines.push('  var mod = __modules[id];');
  lines.push(`  if (!mod) throw new Error("Module not found in combined bundle: " + id + " (in ${submoduleName})");`);
  lines.push('  var m = { exports: {} };');
  lines.push('  __cache[id] = m;');
  lines.push('  mod(m.exports, m, __localRequire(id), __modFilename(id), __modDirname(id));');
  lines.push('  return m.exports;');
  lines.push('}');
  lines.push('');

  // __modDirname/__modFilename: per-module __dirname/__filename
  lines.push('function __modDirname(id) {');
  lines.push('  return require("path").resolve(__dirname, require("path").dirname(id));');
  lines.push('}');
  lines.push('');
  lines.push('function __modFilename(id) {');
  lines.push('  return require("path").resolve(__dirname, id + ".js");');
  lines.push('}');
  lines.push('');

  // __localRequire: per-module require() that resolves intra-submodule requires
  // from the registry, and cross-submodule requires via the target's combined file
  lines.push('function __localRequire(fromId) {');
  lines.push('  var fromDir = require("path").posix.dirname(fromId);');
  lines.push('  return function(reqPath) {');
  lines.push('    if (!reqPath.startsWith(".")) return require(reqPath);');
  lines.push('    var resolved = require("path").posix.normalize(fromDir + "/" + reqPath);');
  lines.push('    if (!resolved.startsWith("./")) resolved = "./" + resolved;');
  lines.push('    if (__modules[resolved]) return __req(resolved);');
  lines.push('    if (__modules[resolved + "/index"]) return __req(resolved + "/index");');
  lines.push('    var absFrom = require("path").resolve(__dirname, fromId + ".js");');
  lines.push('    var absDir = require("path").dirname(absFrom);');
  lines.push('    var absTarget = require("path").resolve(absDir, reqPath);');
  lines.push('    var fs = require("fs");');
  lines.push('    var pkgRoot = require("path").resolve(__dirname, "..");');
  lines.push('    if (absTarget.startsWith(pkgRoot + "/")) {');
  lines.push('      var relFromPkg = absTarget.substring(pkgRoot.length + 1);');
  lines.push('      var parts = relFromPkg.split("/");');
  lines.push('      var targetSubmod = parts[0];');
  lines.push('      var combinedPath = require("path").join(pkgRoot, targetSubmod, "index.combined.js");');
  lines.push('      if (fs.existsSync(combinedPath)) {');
  lines.push('        var targetCombined = require(combinedPath);');
  lines.push('        if (parts.length === 1) return targetCombined;');
  lines.push('        var deepKey = "./" + parts.slice(1).join("/");');
  lines.push('        if (targetCombined.__req) {');
  lines.push('          try { return targetCombined.__req(deepKey); } catch(e) {}');
  lines.push('          try { return targetCombined.__req(deepKey + "/index"); } catch(e) {}');
  lines.push('        }');
  lines.push('      }');
  lines.push('    }');
  lines.push('    return require(absTarget);');
  lines.push('  };');
  lines.push('}');
  lines.push('');

  // Register all modules
  for (const [key, source] of modules) {
    lines.push(`__modules["${key}"] = function(exports, module, require, __filename, __dirname) {`);
    lines.push(source);
    lines.push('};');
    lines.push('');
  }

  // Lazy Proxy export to avoid circular dep issues between combined files
  lines.push('module.exports.__req = __req;');
  lines.push('var __indexLoaded = false, __indexExports;');
  lines.push('function __getIndex() {');
  lines.push('  if (!__indexLoaded) { __indexLoaded = true; __indexExports = __req("./index"); }');
  lines.push('  return __indexExports;');
  lines.push('}');
  lines.push('module.exports = new Proxy(module.exports, {');
  lines.push('  get: function(target, prop) {');
  lines.push('    if (prop === "__req") return __req;');
  lines.push('    if (prop === "__esModule") return __getIndex().__esModule;');
  lines.push('    var idx = __getIndex();');
  lines.push('    return idx[prop];');
  lines.push('  },');
  lines.push('  getOwnPropertyDescriptor: function(target, prop) {');
  lines.push('    if (prop === "__req") return { configurable: true, enumerable: true, value: __req };');
  lines.push('    var idx = __getIndex();');
  lines.push('    if (prop in idx) return { configurable: true, enumerable: true, get: function() { return idx[prop]; } };');
  lines.push('  },');
  lines.push('  ownKeys: function() {');
  lines.push('    return ["__req"].concat(Object.keys(__getIndex()));');
  lines.push('  },');
  lines.push('  has: function(target, prop) {');
  lines.push('    return prop === "__req" || prop in __getIndex();');
  lines.push('  }');
  lines.push('});');

  return lines.join('\n');
}

export interface CombineResult {
  /** Number of modules combined */
  moduleCount: number;
  /** Absolute paths of source .js files that were combined into the chunk */
  sourceFiles: string[];
}

/**
 * Combine a single submodule: read all .js files, generate the combined file.
 * When outputDir is set, also copies data files (.json) referenced by the source.
 *
 * @param outputDir - If provided, write the combined file here instead of in-place.
 *                    The file is written at `<outputDir>/<submoduleName>/index.combined.js`.
 */
export function combineSubmodule(host: IFilesystemHost, submoduleDir: string, submoduleName: string, outputDir?: string): CombineResult | undefined {
  const { sourceFiles, dataFiles } = collectFiles(host, submoduleDir);
  if (sourceFiles.length === 0) return undefined;

  const modules = new Map<string, string>();
  for (const filePath of sourceFiles) {
    const key = registryKey(filePath, submoduleDir);
    let source = host.readFile(filePath);
    source = source.replace(/\/\/# sourceMappingURL=.*$/gm, '');
    source = rewriteRequires(source);
    modules.set(key, source);
  }

  const outBase = outputDir ? path.join(outputDir, submoduleName) : submoduleDir;
  const outputPath = path.join(outBase, 'index.combined.js');
  const content = minifySource(generateCombinedSource(submoduleName, modules));
  host.writeFile(outputPath, content);

  if (outputDir) {
    const pkgRoot = path.dirname(submoduleDir);
    for (const dataFile of dataFiles) {
      const rel = path.relative(pkgRoot, dataFile);
      host.writeFile(path.join(outputDir, rel), host.readFile(dataFile));
    }
  }

  return { moduleCount: modules.size, sourceFiles };
}

/**
 * Delete source .js files that were combined into chunks, except those
 * that are also entry point wrappers (which were overwritten by generateEntryPoints).
 *
 * This is for in-place mode only (mutually exclusive with --out).
 *
 * @returns Number of files deleted.
 */
export function cleanSourceFiles(host: IFilesystemHost, allSourceFiles: string[], entryPointFiles: Set<string>): number {
  let count = 0;
  for (const file of allSourceFiles) {
    if (!entryPointFiles.has(file)) {
      host.deleteFile(file);
      count++;
    }
  }
  return count;
}

/**
 * Discover submodule directories: top-level dirs under root that contain an index.js.
 */
export function discoverSubmodules(host: IFilesystemHost, root: string): string[] {
  return host.readdir(root)
    .filter(e => {
      if (!e.isDirectory) return false;
      if (e.name === 'node_modules' || e.name === 'scripts' || e.name.startsWith('.')) return false;
      return host.exists(path.join(root, e.name, 'index.js'));
    })
    .map(e => e.name)
    .sort();
}

/**
 * Generate wrapper entry point files for each export in package.json.
 *
 * Each wrapper is a small .js file that loads the combined chunk file
 * for its submodule and re-exports the appropriate internal module via __req.
 *
 * @param outputDir - If provided, write wrappers here and look for combined files here.
 *                    The package.json is always read from `root`.
 * @returns List of absolute paths of generated wrapper files.
 */
export function generateEntryPoints(host: IFilesystemHost, root: string, outputDir?: string): string[] {
  const pkg = JSON.parse(host.readFile(path.join(root, 'package.json')));
  const pkgExports: Record<string, string> = pkg.exports ?? {};
  const generated: string[] = [];
  const outRoot = outputDir ?? root;

  for (const [_key, value] of Object.entries(pkgExports)) {
    if (!value.endsWith('.js')) continue;

    const relPath = value.replace(/^\.\//, '');
    const submodule = relPath.split('/')[0];
    const combinedFile = path.join(outRoot, submodule, 'index.combined.js');

    if (!host.exists(combinedFile)) continue;

    const afterSubmodule = relPath.substring(submodule.length + 1);
    const reqKey = './' + afterSubmodule.replace(/\.js$/, '');

    const wrapperAbsPath = path.join(outRoot, relPath);
    const wrapperDir = path.dirname(wrapperAbsPath);
    let combinedRelative = path.relative(wrapperDir, path.join(outRoot, submodule, 'index.combined')).replace(/\\/g, '/');
    if (!combinedRelative.startsWith('.')) {
      combinedRelative = './' + combinedRelative;
    }

    const content = `"use strict";\nmodule.exports = require("${combinedRelative}").__req("${reqKey}");\n`;
    host.writeFile(wrapperAbsPath, content);
    generated.push(wrapperAbsPath);
  }

  return generated;
}

/**
 * Copy the root index.js to the output directory.
 * Only needed when writing to a separate output directory.
 *
 * @returns Number of files copied.
 */
export function copySupportingFiles(host: IFilesystemHost, root: string, outputDir: string): number {
  let count = 0;
  const rootIndex = path.join(root, 'index.js');
  if (host.exists(rootIndex)) {
    host.writeFile(path.join(outputDir, 'index.js'), host.readFile(rootIndex));
    count++;
  }
  return count;
}

/**
 * Minify JavaScript source using esbuild.
 * Uses whitespace and syntax minification only — identifiers are preserved
 * so that the module registry keys and runtime infrastructure remain intact.
 */
export function minifySource(source: string): string {
  const result = transformSync(source, {
    minifyWhitespace: true,
    minifySyntax: true,
    keepNames: true,
  });
  return result.code;
}
